$(document).ready(function(){
    $("#development-image").click(function(){
        $("#development-image").slideDown('500').hide('1000');
        $("#development-image").show('1500');
    });
    $("#development-image").click(function(){
        $("#development-image").slideUp('1500');
        $("#development-image").slideDown('1500');
    });
}) 
